import type { OcrPage } from "../../drizzle/schema";

/**
 * Synthetic demo documents (spec §10).
 *
 * Each demo document is a real (minimal) PDF whose visible text includes a
 * marker line `TRIAGE-SYNTHETIC:<id>`. The demo OCR provider recognizes that
 * marker and returns realistic OCR text; the deterministic extractor then
 * parses that text like it would any other document. Dates are generated
 * relative to "now" so the demo never goes stale.
 *
 * Demo documents can never contact a real third party: every address uses
 * the reserved `.example` TLD.
 */

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

function addDays(base: Date, days: number): Date {
  return new Date(base.getTime() + days * 24 * 60 * 60 * 1000);
}

function formatDate(date: Date): string {
  return `${MONTHS[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;
}

// ---------------------------------------------------------------------------
// Minimal PDF writer (uncompressed, single font, Helvetica). Enough to
// produce a valid, openable PDF containing the document text.
// ---------------------------------------------------------------------------

function escapePdfText(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

export function makeSimplePdf(lines: string[]): Buffer {
  const contentLines = lines
    .map((line, index) => {
      const escaped = escapePdfText(line);
      return index === 0
        ? `(${escaped}) Tj`
        : `(${escaped}) Tj T*`;
    })
    .join("\n");

  const content = `BT\n/F1 11 Tf\n50 742 Td\n16 TL\n${contentLines}\nET`;
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R " +
      "/Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${Buffer.byteLength(content, "latin1")} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, "latin1"));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "latin1");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  }
  pdf +=
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n` +
    `startxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, "latin1");
}

// ---------------------------------------------------------------------------
// Document specs
// ---------------------------------------------------------------------------

export type SyntheticBuiltDocument = {
  id: string;
  filename: string;
  mimeType: "application/pdf";
  pdfBytes: Buffer;
  ocrPages: OcrPage[];
};

export type SyntheticSpec = {
  id: string;
  filename: string;
  /** Visible PDF text lines (includes the synthetic marker). */
  buildLines(now: Date): string[];
  /** What the demo OCR provider "reads" from the document. */
  buildOcrPages(now: Date): OcrPage[];
};

export const SYNTHETIC_DOCUMENTS: SyntheticSpec[] = [
  {
    id: "insurance-renewal",
    filename: "northstar-plan-renewal-notice.pdf",
    buildLines(now) {
      const deadline = formatDate(addDays(now, 4));
      return [
        "TRIAGE-SYNTHETIC:insurance-renewal",
        "SYNTHETIC DEMO DOCUMENT - generated by Triage-Life. Not a real notice.",
        "",
        "NORTHSTAR HEALTH INSURANCE",
        "Plan renewal notice - family plan",
        `Policy holder: Alex Rivera`,
        `Policy number: NH-FAM-40218`,
        `Renewal term: October 1, ${now.getFullYear()} to September 30, ${now.getFullYear() + 1}`,
        "",
        "CURRENT PREMIUM: EUR 180.40 per month",
        "NEW PREMIUM: EUR 214.60 per month (change: +EUR 34.20 per month)",
        "",
        `DECISION REQUIRED: Confirm the renewal on the current plan, or request`,
        "plan alternatives and their premiums, before the deadline.",
        `DEADLINE: ${deadline}`,
        "SEND TO: renewals@northstar-health.example",
      ];
    },
    buildOcrPages(now) {
      const deadline = formatDate(addDays(now, 4));
      return [
        {
          pageNumber: 1,
          confidence: 0.97,
          text: [
            "TRIAGE-SYNTHETIC:insurance-renewal",
            "[Synthetic demo document - generated by Triage-Life]",
            "NORTHSTAR HEALTH INSURANCE",
            "Plan renewal notice - family plan",
            "Policy holder: Alex Rivera",
            "Policy number: NH-FAM-40218",
            `Renewal term: October 1, ${now.getFullYear()} to September 30, ${now.getFullYear() + 1}`,
            "CURRENT PREMIUM: EUR 180.40 per month",
            "NEW PREMIUM: EUR 214.60 per month (change: +EUR 34.20 per month)",
            "DECISION REQUIRED: Confirm the renewal on the current plan, or request plan alternatives and their premiums, before the deadline.",
            `DEADLINE: ${deadline}`,
            "SEND TO: renewals@northstar-health.example",
          ].join("\n"),
        },
        {
          pageNumber: 2,
          confidence: 0.94,
          text: [
            "[Synthetic demo document - generated by Triage-Life]",
            "Questions about your renewal? Email renewals@northstar-health.example",
            "or call 555-0100 (Mon-Fri, 9:00-17:00).",
            "If we do not hear from you before the deadline, the plan renews",
            "automatically at the new premium.",
          ].join("\n"),
        },
      ];
    },
  },
  {
    id: "school-form",
    filename: "riverside-emergency-contact-form.pdf",
    buildLines(now) {
      const deadline = formatDate(addDays(now, 2));
      return [
        "TRIAGE-SYNTHETIC:school-form",
        "SYNTHETIC DEMO DOCUMENT - generated by Triage-Life. Not a real form.",
        "",
        "RIVERSIDE PRIMARY SCHOOL",
        "Emergency contact form - new school year",
        "Student: Maya Rivera, Grade 3B",
        "Primary emergency contact: Alex Rivera (parent) - 555-0142",
        "",
        "MISSING: Secondary emergency contact (name and phone number)",
        "The form cannot be submitted without a secondary contact.",
        "",
        `DEADLINE: ${deadline}`,
        "DELIVERY: Reply by email or submit through the school portal",
        "SEND TO: office@riverside-primary.example",
      ];
    },
    buildOcrPages(now) {
      const deadline = formatDate(addDays(now, 2));
      return [
        {
          pageNumber: 1,
          confidence: 0.96,
          text: [
            "TRIAGE-SYNTHETIC:school-form",
            "[Synthetic demo document - generated by Triage-Life]",
            "RIVERSIDE PRIMARY SCHOOL",
            "Emergency contact form - new school year",
            "Student: Maya Rivera, Grade 3B",
            "Primary emergency contact: Alex Rivera (parent) - 555-0142",
            "MISSING: Secondary emergency contact (name and phone number)",
            "The form cannot be submitted without a secondary contact.",
            `DEADLINE: ${deadline}`,
            "DELIVERY: Reply by email or submit through the school portal",
            "SEND TO: office@riverside-primary.example",
          ].join("\n"),
        },
      ];
    },
  },
  {
    id: "appointment-confirmation",
    filename: "westside-clinic-appointment-confirmation.pdf",
    buildLines(now) {
      const appointment = addDays(now, 8);
      return [
        "TRIAGE-SYNTHETIC:appointment-confirmation",
        "SYNTHETIC DEMO DOCUMENT - generated by Triage-Life. Not a real letter.",
        "",
        "WESTSIDE CLINIC",
        "Appointment confirmation",
        "Patient: Alex Rivera",
        `APPOINTMENT: ${formatDate(appointment)} at 10:30`,
        "LOCATION: Westside Clinic, Room 4, 12 Harbor Street",
        "With: Dr. Mira Patel - annual check-up",
        "",
        "No reply is required. Please arrive 10 minutes early.",
        "ACTION: Add a reminder the evening before.",
      ];
    },
    buildOcrPages(now) {
      const appointment = addDays(now, 8);
      return [
        {
          pageNumber: 1,
          confidence: 0.98,
          text: [
            "TRIAGE-SYNTHETIC:appointment-confirmation",
            "[Synthetic demo document - generated by Triage-Life]",
            "WESTSIDE CLINIC",
            "Appointment confirmation",
            "Patient: Alex Rivera",
            `APPOINTMENT: ${formatDate(appointment)} at 10:30`,
            "LOCATION: Westside Clinic, Room 4, 12 Harbor Street",
            "With: Dr. Mira Patel - annual check-up",
            "No reply is required. Please arrive 10 minutes early.",
            "ACTION: Add a reminder the evening before.",
          ].join("\n"),
        },
      ];
    },
  },
];

export function findSyntheticSpec(id: string): SyntheticSpec | undefined {
  return SYNTHETIC_DOCUMENTS.find(spec => spec.id === id);
}

/** Build the demo PDF + canned OCR for a synthetic document, as of `now`. */
export function buildSyntheticDocument(
  id: string,
  now = new Date(),
): SyntheticBuiltDocument | undefined {
  const spec = findSyntheticSpec(id);
  if (!spec) return undefined;
  return {
    id: spec.id,
    filename: spec.filename,
    mimeType: "application/pdf",
    pdfBytes: makeSimplePdf(spec.buildLines(now)),
    ocrPages: spec.buildOcrPages(now),
  };
}
